name: Upload to Crowdin

on:
  push:
    branches:
    - master

permissions: {}

jobs:
  upload:
    environment: dev-crowdin
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Upload latest strings for translation on Crowdin
      uses: crowdin/github-action@v2
      with:
        crowdin_branch_name: master
        config: 'crowdin.yml'
        token: ${{ secrets.CROWDIN_API_TOKEN }}
